#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
variable_list = [1,2,1,3,4]
print(variable_list)

[1, 2, 1, 3, 4]


In [11]:
array = [1,2,1,4,5,3]

import numpy as np

array_list = np.array(array)
array_list

array([1, 2, 1, 4, 5, 3])

In [ ]:
In Python, variable names are not tied to specific data types, but rather the objects they reference have types. 
If you have variables named variable_list and array_list their data types will depend on what objects they reference.

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
type(variable_list)

for i in variable_list:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [13]:
type(array_list)

for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Q3. Considering the following changes in the variable, array_list:

In [19]:
array_list = np.array(object = variable_list, dtype = int)
array_list

for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [18]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

for i in num_array:
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### Q4. Write a code to find the following characteristics of variable, num_array:

In [20]:
# shape
array_list.shape

(5,)

In [21]:
# Size

array_list.size

5

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [22]:
p = np.zeros((3,3))

In [23]:
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
np.diag([1,1,1,1,1]) 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])